server:
  port: 8080

spring:
  application:
    name: Wallet-Service

  datasource:
    url: jdbc:postgresql://localhost:5436/Wallet_Service_db
    username: ivan
    password: 123
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: db/changelog/changelog.xml
    default-schema: migration

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

  security:
    jwt:
      secret: cGFzc3dvcmRmb3JJdmFuZ2lnYWNoYWRvdmljaA==
      access: 3600000

logging:
  level:
    root: INFO